#1. Environment Setup

In [14]:
# Import NumPy library
import numpy as np

print(f"NumPy Version: {np.__version__}")

NumPy Version: 2.0.2


#2. Creating 1D, 2D, and 3D Arrays

In [15]:
# 1D Array (Vector)
arr_1d = np.array([10, 20, 30, 40, 50])
print("--- 1D Array ---")
print(arr_1d)

# 2D Array (Matrix - 3 rows, 3 columns)
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("\n--- 2D Array ---")
print(arr_2d)

# 3D Array (Tensor - 2 blocks of 2 rows and 3 columns)
arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print("\n--- 3D Array ---")
print(arr_3d)

--- 1D Array ---
[10 20 30 40 50]

--- 2D Array ---
[[1 2 3]
 [4 5 6]
 [7 8 9]]

--- 3D Array ---
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#3. Checking Array Dimensions, Shapes, and Data Types

In [16]:
def inspect_array(name, arr):
    print(f"--- Inspecting {name} ---")
    print(f"Content:\n{arr}")
    print(f"Number of dimensions (ndim) : {arr.ndim}")
    print(f"Shape (shape)              : {arr.shape}")
    print(f"Total elements (size)       : {arr.size}")
    print(f"Data type (dtype)          : {arr.dtype}\n")

inspect_array("1D Array", arr_1d)
inspect_array("2D Array", arr_2d)
inspect_array("3D Array", arr_3d)

--- Inspecting 1D Array ---
Content:
[10 20 30 40 50]
Number of dimensions (ndim) : 1
Shape (shape)              : (5,)
Total elements (size)       : 5
Data type (dtype)          : int64

--- Inspecting 2D Array ---
Content:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Number of dimensions (ndim) : 2
Shape (shape)              : (3, 3)
Total elements (size)       : 9
Data type (dtype)          : int64

--- Inspecting 3D Array ---
Content:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Number of dimensions (ndim) : 3
Shape (shape)              : (2, 2, 3)
Total elements (size)       : 12
Data type (dtype)          : int64



#4. Generating Arrays using Built-in Functions

In [17]:
# 1. Zeros array
zeros_arr = np.zeros((2, 4))
print("Zeros (2x4):\n", zeros_arr)

# 2. Ones array with integer data type
ones_arr = np.ones((3, 2), dtype=int)
print("\nOnes (3x2, int):\n", ones_arr)

# 3. arange() - start, stop (exclusive), step
range_arr = np.arange(0, 20, 2)
print("\narange(0, 20, step=2):\n", range_arr)

# 4. linspace() - start, stop (inclusive), number of points
linear_arr = np.linspace(0, 1, 5)
print("\nlinspace(0, 1, 5 points):\n", linear_arr)

# 5. Full array & Identity matrix
full_arr = np.full((2, 3), 7)
eye_arr = np.eye(3)
print("\nFull Array (2x3 filled with 7):\n", full_arr)
print("\nIdentity Matrix (3x3):\n", eye_arr)

Zeros (2x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones (3x2, int):
 [[1 1]
 [1 1]
 [1 1]]

arange(0, 20, step=2):
 [ 0  2  4  6  8 10 12 14 16 18]

linspace(0, 1, 5 points):
 [0.   0.25 0.5  0.75 1.  ]

Full Array (2x3 filled with 7):
 [[7 7 7]
 [7 7 7]]

Identity Matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#5. Indexing and Slicing

In [18]:
# --- 1D Indexing & Slicing ---
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print("Original 1D:", arr)
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Elements index 2 to 4:", arr[2:5])
print("Every second element:", arr[::2])

# --- 2D Indexing & Slicing ---
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print("\nOriginal 2D Matrix:\n", matrix)
print("Element at row 1, col 2:", matrix[1, 2])       # Output: 60
print("First row:", matrix[0, :])                       # Row 0, all cols
print("Last column:", matrix[:, -1])                    # All rows, column -1
print("Sub-matrix (top-left 2x2):\n", matrix[0:2, 0:2])

Original 1D: [10 20 30 40 50 60 70]
First element: 10
Last element: 70
Elements index 2 to 4: [30 40 50]
Every second element: [10 30 50 70]

Original 2D Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at row 1, col 2: 60
First row: [10 20 30]
Last column: [30 60 90]
Sub-matrix (top-left 2x2):
 [[10 20]
 [40 50]]


#6. Reshaping Arrays

In [19]:
# Create a 1D array of 12 elements
flat_arr = np.arange(1, 13)
print("Original Flat Array:\n", flat_arr)

# Reshape into 3x4 2D matrix
matrix_3x4 = flat_arr.reshape(3, 4)
print("\nReshaped to (3, 4):\n", matrix_3x4)

# Reshape into 2x2x3 3D array
tensor_2x2x3 = flat_arr.reshape(2, 2, 3)
print("\nReshaped to (2, 2, 3):\n", tensor_2x2x3)

# Flattening back to 1D
flattened = matrix_3x4.ravel()
print("\nFlattened back using ravel():\n", flattened)

Original Flat Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to (3, 4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped to (2, 2, 3):
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Flattened back using ravel():
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


#7. Mathematical and Vectorized Operations

In [20]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

# Vectorized Arithmetic
print("a + b :", a + b)
print("a - b :", a - b)
print("a * b :", a * b)
print("a / b :", a / b)
print("a ** 2:", a ** 2)

# Vectorized Universal Functions (ufuncs)
angles = np.array([0, np.pi/4, np.pi/2])
print("\nSin of angles:", np.sin(angles))
print("Exponential (exp) of b:", np.exp(b))
print("Square root of a:", np.sqrt(a))

a + b : [11 22 33 44]
a - b : [ 9 18 27 36]
a * b : [ 10  40  90 160]
a / b : [10. 10. 10. 10.]
a ** 2: [ 100  400  900 1600]

Sin of angles: [0.         0.70710678 1.        ]
Exponential (exp) of b: [ 2.71828183  7.3890561  20.08553692 54.59815003]
Square root of a: [3.16227766 4.47213595 5.47722558 6.32455532]


#8. Boolean Masking and Filtering

In [21]:
data = np.array([15, 8, 42, 4, 23, 16, 9, 30])
print("Data:", data)

# Create a boolean condition
mask = data > 20
print("\nBoolean Mask (data > 20):\n", mask)

# Filter elements using mask
filtered_data = data[mask]
print("Filtered Data (values > 20):", filtered_data)

# Modifying values conditionally
data_copy = data.copy()
data_copy[data_copy < 10] = 0
print("Replaced values < 10 with 0:", data_copy)

# np.where(condition, x, y) -> if condition True, x, else y
binary_classification = np.where(data >= 20, "High", "Low")
print("np.where Labeling:", binary_classification)

Data: [15  8 42  4 23 16  9 30]

Boolean Mask (data > 20):
 [False False  True False  True False False  True]
Filtered Data (values > 20): [42 23 30]
Replaced values < 10 with 0: [15  0 42  0 23 16  0 30]
np.where Labeling: ['Low' 'Low' 'High' 'Low' 'High' 'Low' 'Low' 'High']


#9. Broadcasting

In [22]:
# Example 1: Scalar and Array Broadcasting
matrix = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10
print("Matrix + Scalar (10):\n", matrix + scalar)

# Example 2: 1D Array and 2D Array Broadcasting
# 2D Array shape: (3, 3)
grid = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# 1D Array shape: (3,)
row_vec = np.array([1, 2, 3])

print("\nGrid (3x3):\n", grid)
print("Row Vector (3,):\n", row_vec)
print("\nGrid + Row Vector (Broadcasting across rows):\n", grid + row_vec)

Matrix + Scalar (10):
 [[11 12 13]
 [14 15 16]]

Grid (3x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Row Vector (3,):
 [1 2 3]

Grid + Row Vector (Broadcasting across rows):
 [[11 22 33]
 [41 52 63]
 [71 82 93]]


#10. Aggregate Functions

In [23]:
numbers = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Matrix:\n", numbers)
print("\n--- Global Aggregations ---")
print("Sum    :", np.sum(numbers))
print("Mean   :", np.mean(numbers))
print("Min    :", np.min(numbers))
print("Max    :", np.max(numbers))
print("Median :", np.median(numbers))
print("Std Dev:", np.std(numbers))

print("\n--- Axis-specific Aggregations ---")
# axis=0: along columns (downwards)
print("Column-wise Sum (axis=0) :", np.sum(numbers, axis=0))
print("Column-wise Mean (axis=0):", np.mean(numbers, axis=0))

# axis=1: along rows (across)
print("Row-wise Sum (axis=1)    :", np.sum(numbers, axis=1))
print("Row-wise Max (axis=1)    :", np.max(numbers, axis=1))

Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

--- Global Aggregations ---
Sum    : 450
Mean   : 50.0
Min    : 10
Max    : 90
Median : 50.0
Std Dev: 25.81988897471611

--- Axis-specific Aggregations ---
Column-wise Sum (axis=0) : [120 150 180]
Column-wise Mean (axis=0): [40. 50. 60.]
Row-wise Sum (axis=1)    : [ 60 150 240]
Row-wise Max (axis=1)    : [30 60 90]
